image:
- Visual Studio 2015
- Ubuntu


environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  PY_DIR: C:\Python36-x64

clone_depth: 3

before_build:
- cmd: set PATH=%MINGW_DIR%;%PY_DIR%;%PATH%
# fix CMake sh.exe issue, by removing Git path.
- cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
- cmd: set FC=%MINGW_DIR%\gfortran
- cmd: set CXX=%MINGW_DIR%\g++
- cmd: set CC=%MINGW_DIR%\gcc

- sh: sudo apt install -q -y g++ gfortran cmake make

- cd bin

build_script:
- cmd: cmake -G "MinGW Makefiles" ..
- cmd: mingw32-make

- sh: cmake ..
- sh: make
  
after_build:
- ./hellocpp
- ./hellof

- cd ..
- python hello.py

on_failure:
- cmd: type bin\CMakeFiles\CMakeError.log
