language: cpp
fast_finish: true

os:
  - linux
  - osx
  
env: FC=gfortran

group: travis_latest


git:
  depth: 3

addons:
  apt:
    packages:
      - g++
      - gfortran

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc || true;
      brew link --overwrite gcc;
      export FC=gfortran;
    fi

install: 
  - cd bin
  - cmake ..
  - make
    
script:
  - make test
