environment:
  MINGW_DIR: mingw64
  MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z/download
  MINGW_ARCHIVE: x86_64-6.3.0-posix-seh-rt_v5-rev1.7z


clone_depth: 3

install:
- if not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
- 7z x -y "%MINGW_ARCHIVE%" > nul

before_build:
- set Path=%CD%\%MINGW_DIR%\bin;%Path%
- gcc --version
- echo %CC%
- g++ --version
- echo %CXX%
- gfortran --version
- echo %FC%
- mingw32-make --version
- cmake --version
- set ORIGPATH=%PATH%



build_script:
  - cd bin
  
  - set PATH=C:\Program Files (x86)\CMake\bin
  - cmake .. -G "MinGW Makefiles" 
  
  - set PATH=%OLDPATH%
  - make
