environment:
  CC:  C:\msys64\mingw64\bin\gcc.exe
  CXX: C:\msys64\mingw64\bin\g++.exe
  FC:  C:\msys64\mingw64\bin\gfortran.exe

clone_depth: 3

init:  
- set ORIGPATH=%PATH%


before_build:
- g++ --version
- mingw32-make --version
- cmake --version

build_script:
  - cd bin
  
  - set PATH=C:\Program Files (x86)\CMake\bin
  - cmake .. -G "MinGW Makefiles" 
  
  - set PATH=%OLDPATH%
  - make
