environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

clone_depth: 3

before_build:
- set PATH=%MINGW_DIR%;%PATH%

# fix CMake sh.exe issue,  https://github.com/jibsen/brieflz/blob/0c6fb73984f11e697dfaade5cdc5e291c1655c67/appveyor.yml
- set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
- set PATH=C:\MinGW\bin;%PATH%

- set CC=%MINGW_DIR%\gcc.exe
- set CXX=%MINGW_DIR%\g++.exe
- set FC=%MINGW_DIR%\gfortran.exe

- cd bin

build_script:
- cmake -G "MinGW Makefiles" ..
- mingw32-make
  
after_build:
- hellocpp.exe
- hellof.exe

on_failure:
- type CMakeFiles\CMakeError.log
