environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  PY_DIR: C:\Python36-x64\bin

clone_depth: 3

before_build:
- set PATH=%MINGW_DIR%;%PY_DIR%;%PATH%
# fix CMake sh.exe issue, by removing Git path.
- set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

- set CC=%MINGW_DIR%\gcc.exe
- set CXX=%MINGW_DIR%\g++.exe
- set FC=%MINGW_DIR%\gfortran.exe

- cd bin

build_script:
- cmake -G "MinGW Makefiles" ..
- mingw32-make
  
after_build:
- hellocpp.exe
- hellof.exe

- cd ..
- python hello.py

on_failure:
- type CMakeFiles\CMakeError.log
